### ISSUE TITLE
Add issues/q to gganimate at will

### ISSUE THREAD

**Issue by thomasp85** [ropenscilabs/learngganimate#1]
This is amazing. Please, if you stumble on something that you think should work, but doesn't (e.g. transition_filter should work with a logical column from the data) please open an issue

Also if there's question about behaviour (e.g. `keep` in transition_filter) feel free to ping me on twitter or open an issue as well

:-)

**Comment by adam-gruer** [comment]
Thanks @thomasp85 will do! We've had a lot of fun today!

**Comment by annaquaglieri16** [comment]
Thanks for your feedback @thomasp85!!. And I have to say that was my mistake! The TRUE/FALSE column as logical condition actually works 😉 so will update that with examples.  Not sure still about  `keep` so will add an issue.
