### ISSUE TITLE
add a toc to each Rmd file

### ISSUE THREAD

**Issue by adam-gruer** [ropenscilabs/learngganimate#10]
Anna, I noticed in your rmarkdowns you had a table of contents in your YAML.  It was really cool.
I'm being lazy asking you to add them in to everybody's .Rmd files

**Comment by annaquaglieri16** [comment]
Hey Adam, sounds good. Happy to do that. Maybe after next week of conferences!

**Comment by adam-gruer** [comment]
Great 🥳  I know you will look forward to the ‘closing the issue’ buzz 💯

**Comment by will-r-chase** [comment]
By the way, there's some nice automatic generators for github docs. That's what I used for mine. 

https://github.com/thlorenz/doctoc
http://tableofcontent.eu/
