### ISSUE TITLE
knit docs using cairo device to update with Jesse's edits

### ISSUE THREAD

**Issue by adam-gruer** [ropenscilabs/learngganimate#17]
The fabulous @jmostipak did some editing of typos and grammar for us.  She edited the .Rmd source files in PR   #15  and I am re-knitting the files she touched up.  However I am having trouble knitting the ones that use `type = "cairo"` in the `animate` function.  The cairo device is not available to me on a Mac without building R with brew or conda and other such ridiculousness. So when someone has the time  and a windows (maybe linux?) machine can they knit the following files and push up to github.
I'll probably create an issue to add a page describing that animate function and the type parameter and devices.  there is already some good notes in the shadow_wake.Rmd discussion - which should be 'borrowed' and extended see #18 #
the files that need to be re-knit are

- shadow_wake.Rmd

- view_follow.Rmd

**Comment by jmostipak** [comment]
I went ahead and knit these and will submit them!
