### ISSUE TITLE
do a write up of the animate function and its arguments

### ISSUE THREAD

**Issue by adam-gruer** [ropenscilabs/learngganimate#18]
Worth pulling together various discussion and examples from existing .Rmd and collate a decription about when, why to use thus function and the various arguments including `...` args that are passed to other methods e.g. `type` also see #17

**Comment by will-r-chase** [comment]
Happy to help if no one else has this one. I'll be starting on it today

**Comment by will-r-chase** [comment]
@adam-gruer is there any objection to rendering the animate tutorial as an html doc instead of github doc? The tutorial shows how to render videos instead of gifs, but I don't think github docs are capable of showing videos.

**Comment by adam-gruer** [comment]
I don't think there is an objection @will-r-chase .
I think the reason we were going for github_docs is that they render within github.  Whereas sometimes html files you get that ```this file is too large``` complaint if that makes sense.
It's not a deal breaker or anything so give it a shot as html

**Comment by will-r-chase** [comment]
Indeed, I got the file too large problem. No worries, I'll just move back to github docs and leave videos as external links.

**Comment by adam-gruer** [comment]
Closing because @will-r-chase is amazing - see 55cbbd555386511eb1f0c80fe4c5a0e0ecf52920 and parent commits and the output https://github.com/ropenscilabs/learngganimate/blob/master/animate.md
