### ISSUE TITLE
Add guide to animate() start_pause and end_pause arguments

### ISSUE THREAD

**Issue by ekothe** [ropenscilabs/learngganimate#28]
As per twitter...
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">animate() now has a start_pause and end_pause argument to allow you to repeat the first and last frame a number of times, as well as a rewind argument to allow the animation to rewind</p>&mdash; Thomas Lin Pedersen (@thomasp85) <a href="https://twitter.com/thomasp85/status/1070244318802313217?ref_src=twsrc%5Etfw">December 5, 2018</a></blockquote>

**Comment by will-r-chase** [comment]
thanks for the reminder! I saw Thomas's tweet and was planning to update the animate and renderer tutorial. I just need to get the inertia to reinstall newest version of gganimate, which is a certain type of masochism for a windows user
