### ISSUE TITLE
make an installation guide

### ISSUE THREAD

**Issue by will-r-chase** [ropenscilabs/learngganimate#32]
installing gganimate gave me a lot of trouble (windows user) in the beginning... might be good to write a guide

**Comment by adam-gruer** [comment]
Yes - so a couple of things that have caused issues for various people during and post the start of this project

- not having the CRAN release of  `tweenr` caused problems 
- not having the latest github version of `transformr` caused problems 

It's all understandable after the fact,  this is a development package after all, but they are still real hard to troubleshoot .  
this may all be settling down as I note `transformr` CRAN release announced today and is part of Thomas' plan for `gganimate` but documenting some of the pain points will be helpful.  I must admit to being guilty of eventually finding the fix but not writing it down which does not benefit future me or anybody else.
