### ISSUE TITLE
API breaking change. Update required for articles that use transition_components() or transition_reveal()

### ISSUE THREAD

**Issue by adam-gruer** [ropenscilabs/learngganimate#34]
Code using these functions will need to be updated and the Rmd  source files re knitted.

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/hashtag/gganimate?src=hash&amp;ref_src=twsrc%5Etfw">#gganimate</a> has experienced a small (but very breaking) change… The `id` argument hof transition_components() and transition_reveal() has been deprecated in favour of using group aesthetic in each layer <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a></p>&mdash; Thomas Lin Pedersen (@thomasp85) <a href="https://twitter.com/thomasp85/status/1072081961378811906?ref_src=twsrc%5Etfw">December 10, 2018</a></blockquote>

**Comment by annaquaglieri16** [comment]
Hey Adam! I modified the transition_components() part by removing the `id` argument and using the group or colour arguments in the ggplot() call.
