### ISSUE TITLE
Convert the posts to a bookdown book

### ISSUE THREAD

**Issue by adam-gruer** [ropenscilabs/learngganimate#9]

**Comment by annaquaglieri16** [comment]
This is a really cool idea and I am happy to help with that since I wanted to learn it to maybe write my thesis in bookdown. It could be nice to catch up sometimes and discuss on what to do!

**Comment by adam-gruer** [comment]
That is a good idea @annaquaglieri16.  Lets discuss the week after next about perhaps organising a catchup where whoever can make it (and/or zoom ) can work on the move to  bookdown   together
